const mongoose = require('mongoose');

const driverSchema = new mongoose.Schema({
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    phone: { type: String, required: true },
    role: {
        type: String,
        enum: ['driver', 'chaser'], // Role: driver or chaser
        required: true,
    },
    revenue: { type: Number, default: 0 }, // Revenue generated by the driver/chaser
    status: {
        type: String,
        enum: ['active', 'suspended', 'deactivated'], // Account status
        default: 'active',
    },
    location: {
        latitude: { type: Number },
        longitude: { type: Number },
    },
    assignedRide: { type: mongoose.Schema.Types.ObjectId, ref: 'Ride' }, // Ride assignment
});

module.exports = mongoose.model('Driver', driverSchema);